on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: 6fe5c1a5f47c4c67acbf7c06427f5bc8.azurecr.io
        username: ${{ secrets.acr_6fe5c1a5f47c4c67acbf7c06427f5bc8_username }}
        password: ${{ secrets.acr_6fe5c1a5f47c4c67acbf7c06427f5bc8_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/DeployMachineLearningModels/DeployFlaskAzure" -f  "DeployMachineLearningModels/DeployFlaskAzure/Dockerfile" -t 6fe5c1a5f47c4c67acbf7c06427f5bc8.azurecr.io/automlaks4c51737678c:${{ github.sha }} --label dockerfile-path=DeployMachineLearningModels/DeployFlaskAzure/Dockerfile
        docker push 6fe5c1a5f47c4c67acbf7c06427f5bc8.azurecr.io/automlaks4c51737678c:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_automlaks4c51737678c_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep automlaks4c51737678cb227 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace automlaks4c51737678cb227`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: automlaks4c51737678cb227
        container-registry-url: 6fe5c1a5f47c4c67acbf7c06427f5bc8.azurecr.io
        container-registry-username: ${{ secrets.acr_6fe5c1a5f47c4c67acbf7c06427f5bc8_username }}
        container-registry-password: ${{ secrets.acr_6fe5c1a5f47c4c67acbf7c06427f5bc8_password }}
        secret-name: automlaks4c5dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: automlaks4c51737678cb227
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          6fe5c1a5f47c4c67acbf7c06427f5bc8.azurecr.io/automlaks4c51737678c:${{ github.sha }}
        imagepullsecrets: |
          automlaks4c5dockerauth
